name: CI Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - run: npm ci
      - run: npm run lint
  test:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        node: [ 10, 12, 14 ]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - name: build
        run: |
          npm ci
          npm run build
      - name: test
        run: |
          node lib/index.js init test
          cd test
          node ../lib/index.js make
          node ../lib/index.js make --prod
          node ../lib/index.js g c test
          node ../lib/index.js g r test
          node ../lib/index.js make
          node ../lib/index.js make --prod
