name: CI Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 14
      - run: npm ci
      - run: npm run lint
  test:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        node: [ 10, 12, 14 ]
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://npm.pkg.github.com"
          scope: "@alex-sandri"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: |
          npm config set @alex-sandri:registry https://npm.pkg.github.com/
          npm ci
          npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: test
        run: |
          node lib/index.js init test
          cd test
          node ../lib/index.js make
          node ../lib/index.js make --prod
          node ../lib/index.js g c test
          node ../lib/index.js g r test
          node ../lib/index.js make
          node ../lib/index.js make --prod
